#!/bin/bash

mkdir -p /var/run/mysqld/
chown -R mysql:mysql /var/run/mysqld/
chown -R mysql:mysql /var/lib/mysql/

#CREATE DATABASE $MARIADB_NAME;
#CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PWD';
#GRANT ALL PRIVILEGES ON $MARIADB_NAME.* TO $MARIADB_USER@'%' IDENTIFIED BY '$MARIADB_PWD';

#GRANT ALL PRIVILEGES ON $MARIADB_NAME.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;
#GRANT ALL PRIVILEGES ON $MARIADB_NAME.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;
#FLUSH PRIVILEGES;

service mariadb start


mysql -u root -p$MARIADB_ROOT_PWD <<-EOSQL

CREATE DATABASE IF NOT EXISTS $MARIADB_NAME;
CREATE USER IF NOT EXISTS $MARIADB_USER@'%' IDENTIFIED BY '$MARIADB_PWD';

GRANT ALL PRIVILEGES ON $MARIADB_NAME.* TO $MARIADB_USER@'%' IDENTIFIED BY '$MARIADB_PWD';

FLUSH PRIVILEGES;

EOSQL

service mariadb stop

exec "$@"
